nelmio_api_doc:
    models: { use_jms: true }
    documentation:
        info:
            title: '%env(SITE_TITLE)%'
            description: '%env(SITE_DESCRIPTION)%'
            version: 1.0.0
    areas:
        default:
            path_patterns:
                - ^/public # Accepts routes under /api except /api/doc

        collective:
            path_patterns:
                - ^/collective # Accepts routes under /api except /api/doc