nelmio_api_doc:
    documentation:
        info:
            title: '%env(SITE_TITLE)%'
            description: '%env(SITE_DESCRIPTION)%'
            version: 1.0.0
    routes:
        path_patterns:
            - ^/public(?!/doc$) # Accepts routes under /api except /api/doc
