language: php
node_js:
  - "8.2.1"

install:
  - npm install newman
  - composer install

before_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version
  - php ./bin/console server:start

script:
  - ./bin/phpunit
  - node_modules/.bin/newman run postman.json
