language: php
php:
  - '7.2'
node_js:
  - "8.2.1"

install:
  - mkdir translations
  - npm install newman
  - make deploy
  - composer install --dev

before_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version
  - php ./bin/console server:start

script:
  - ./vendor/bin/phpunit
  - node_modules/.bin/newman run postman.json
