language: php
php:
  - '7.2'
  - 'nightly'
node_js:
  - "8.2.1"

install:
  - mkdir translations || true
  - npm install newman
  - make deploy
  - composer install --dev

before_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version
  - php ./bin/console server:start

script:
  - ./vendor/bin/phpunit

  # postman tests are actually allowed to fail
  - node_modules/.bin/newman run postman.json || true
