
## Groups
admin.banner_group.list:
    path: /collective/group
    controller: "App\\Controller\\Management\\ManageGroupsController::listGroupsAction"
    methods: ['GET']

admin.banner_group.create:
    path: /collective/group/create
    controller: "App\\Controller\\Management\\ManageGroupsController::createGroupAction"
    methods: ['POST']

admin.banner_group.modify:
    path: /collective/group/edit/{groupName}
    controller: "App\\Controller\\Management\\ManageGroupsController::editGroupAction"
    methods: ['PUT']

admin.banner_group.delete:
    path: /collective/group/{groupName}
    controller: "App\\Controller\\Management\\ManageGroupsController::deleteAction"
    methods: ['DELETE']


## Elements
admin.banner_element.list:
    path: /collective/element/listing/{groupName}
    controller: "App\\Controller\\Management\\ManageBannersController::listBannersAction"
    methods: ['GET']

admin.banner_element.create:
    path: /collective/element/create/{groupName}
    controller: "App\\Controller\\Management\\ManageBannersController::createBannerAction"
    methods: ['POST']

admin.banner_element.edit:
    path: /collective/element/edit/{bannerId}
    controller: "App\\Controller\\Management\\ManageBannersController::editBannerAction"
    methods: ['PUT']

admin.banner_element.delete:
    path: /collective/element/{bannerId}
    controller: "App\\Controller\\Management\\ManageBannersController::deleteAction"
    methods: ['DELETE']
