App\Domain\Form\GroupForm:
    properties:
        title:
            - NotBlank: ~
            - Length:
                min: 3
                max: 254

        description:
            - Length:
                min: 0
                max: 9000

App\Domain\Form\BannerForm:
    properties:
        url:
            - Url:
                  protocols: ['http', 'https']
                  relativeProtocol: false
            - Length:
                  min: 5
                  max: 256
            - NotBlank: ~

        imageUrl:
            - Url:
                  protocols: ['http', 'https']
                  relativeProtocol: false
            - Length:
                  min: 5
                  max: 256
            - NotBlank: ~

        title:
            - NotBlank: ~
            - Length:
                min: 3
                max: 254

        description:
            - Length:
                min: 0
                max: 9000

        expiresAt:
            - DateTime:
                  format: Y-m-d H:i:s

App\Domain\Form\NewGroupForm:
    properties:
        id:
            - NotBlank: ~
            - Length:
                  min: 3
                  max: 16
