App\Domain\Form\GroupForm:
    properties:
        title:
            - NotBlank: ~
            - Length:
                min: 3
                max: 254

        description:
            - Length:
                min: 0
                max: 9000

        active:
            - NotBlank: ~
            - Type:
                  type: bool
            - Choice: [1, 0, true, false]

App\Domain\Form\BannerForm:
    properties:
        url:
            - Url: ~
            - Length:
                  min: 5
                  max: 256
            - NotBlank: ~

        imageUrl:
            - Url: ~
            - Length:
                  min: 5
                  max: 256
            - NotBlank: ~

        title:
            - NotBlank: ~
            - Length:
                min: 3
                max: 254

        description:
            - Length:
                min: 0
                max: 9000

        active:
            - NotBlank: ~
            - Type:
                  type: bool
            - Choice: [1, 0, true, false]

App\Domain\Form\NewGroupForm:
    properties:
        id:
        - NotBlank: ~
        - Length:
              min: 3
              max: 16

App\Domain\Form\NewBannerForm:
    properties:
        id:
            - NotBlank: ~
            - Length:
                  min: 3
                  max: 16